#!/usr/bin/env python3
"""
Build kjv-glossary.json from Webster's Unabridged Dictionary (1913, public domain).

Every gloss in the output is lifted verbatim from Webster's. Nothing is authored
here and nothing is generated by a model -- the whole point is that each entry
traces back to a real dictionary sense, with the provenance recorded per entry.

Source: an Apple Dictionary.app bundle built from the public-domain Webster's
1913 text. Body.data is a run of zlib streams (0x78 0xda); each decompresses to
XML holding <d:entry> elements with class="def" / "mark" / "au" sub-divs.

Sense selection is derived, never guessed. In priority order:

  cited   a sense whose quotation cites scripture ("Ex. xxvi. 6.") -- Webster
          is telling us directly which sense the KJV uses.
  marked  a sense tagged [Obs.] or [Archaic]. This is what catches the false
          friends: words still current today whose 1611 meaning differs
          (prevent -> go before, leasing -> lying, let -> hinder).
  single  the entry has exactly one sense, so there is nothing to disambiguate.
          Only taken for words that are rare in the KJV itself.

Anything else -- a common word whose KJV sense sits unmarked among several
modern ones (charity, suffer, corn) -- is written to the review file instead of
the glossary. Those need a human to pick the sense; picking one automatically
is how you end up asserting something false about scripture.

Usage:
  python3 scripts/build_glossary.py [--bundle PATH] [--out PATH] [--review PATH]
"""

import argparse
import collections
import html
import json
import os
import re
import sys
import zlib

DEFAULT_BUNDLE = os.path.expanduser(
    "~/Library/Dictionaries/websters-1913.dictionary/Contents/Resources/Body.data"
)
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUT = os.path.join(REPO, "src/main/resources/data/kjv-glossary.json")
DEFAULT_REVIEW = os.path.join(REPO, "scripts/glossary-needs-review.json")
KJV_JSON = os.path.join(REPO, "src/main/resources/data/kjv.json")

# Webster cites scripture as "Ex. xxvi. 6." / "1 Cor. xiii. 4." -- an abbreviated
# book, a roman-numeral chapter, then a verse.
BOOKS = (
    r"(?:Gen|Ex|Exod|Lev|Num|Deut|Josh|Judg|Ruth|Sam|Kings|Kin|Chron|Ezra|Neh|Esth|Job|Ps"
    r"|Prov|Eccl|Cant|Song|Isa|Jer|Lam|Ezek|Dan|Hos|Joel|Amos|Obad|Jonah|Mic|Nah|Hab"
    r"|Zeph|Hag|Zech|Mal|Matt|Mark|Luke|John|Acts|Rom|Cor|Gal|Eph|Phil|Col|Thess|Tim"
    r"|Titus|Philem|Heb|James|Jas|Pet|Jude|Rev)"
)
CITE_RE = re.compile(r"^\s*(?:[1-3]\s*)?" + BOOKS + r"\.?\s*[ivxlc]+[\.\s]", re.I)
ARCHAIC_RE = re.compile(r"\b(obs|archaic)\b", re.I)
WORD_RE = re.compile(r"[A-Za-z][A-Za-z'\-]*")

# Suffixes stripped when mapping an inflected KJV form back to a Webster
# headword: taches -> tache, coupleth -> couple. Longest first so "eth" is
# tried before "th".
SUFFIXES = ["eth", "est", "ing", "es", "ed", "st", "th", "s", "d", "n"]

# Webster carries a long-dead sense for almost every function word -- "god" as a
# variant of "good", "not" as a contraction of "wot not", "me" as a form of
# "men". Selecting those produces a gloss that is both useless and, on a page of
# scripture, actively false. Function words are a closed grammatical class, so
# excluding them wholesale costs nothing: no reader of the KJV is stuck on "the".
FUNCTION_WORDS = set("""
a an the and or but nor for yet so if then than that this these those there here
of in on at by to from with without within into onto upon over under above below
through between among against about after before during until till since up down
out off again further once
i me my mine myself we us our ours ourselves you your yours yourself yourselves
he him his himself she her hers herself it its itself they them their theirs
themselves who whom whose which what whatever whoever whomever
thee thou thy thine ye yourself
am is are was were be been being have has had having do does did doing done
shall should will would may might must can could let lets
not no nor none nothing all any both each few more most other some such only own
same very too as is came come go went gone said say says
""".split())

# Webster's entry body sometimes holds an inflection note rather than a
# definition ("imperfect or past participle", "plural of ..."). Useless in a
# popover, and in a few cases actively misleading.
STUB_RE = re.compile(
    r"^\s*(?:"
    r"imperfect|past\s+participle|present\s+participle|p\.\s*p\b|pl\b|plural\b|sing\b"
    r"|first-?\s*or\s*third-?\s*person|second-?\s*person|third-?\s*person"
    r"|see\s+\w+\.?\s*$|of\s+\w+\.?\s*$|obs\b"
    r")",
    re.I,
)

# Above this many occurrences a word is part of the KJV's ordinary furniture and
# a reader is not tripping over it. Keeps the glossary to words that actually
# stop someone: shew (228) stays, saith (1262) goes.
MAX_OCCURRENCES = 300


def log(msg):
    print(msg, file=sys.stderr)


def decompress_body(path):
    """Concatenate every zlib stream in an Apple Dictionary Body.data."""
    raw = open(path, "rb").read()
    magic = re.compile(rb"\x78[\x01\x9c\xda]")
    out, i, n = [], 0x40, 0
    while True:
        m = magic.search(raw, i)
        if not m:
            break
        j = m.start()
        try:
            dec = zlib.decompressobj()
            chunk = dec.decompress(raw[j:])
            if len(chunk) > 500:
                out.append(chunk)
                n += 1
                i = len(raw) - len(dec.unused_data)
                continue
        except zlib.error:
            pass
        i = j + 2
    log(f"  {n} zlib streams -> {sum(len(c) for c in out):,} bytes of XML")
    return b"".join(out).decode("utf-8", "replace")


def untag(s):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", s))).strip()


def parse_entries(blob):
    """headword -> [sense], each sense carrying its def, marker and citation."""
    words = collections.defaultdict(list)
    for entry in re.split(r"(?=<d:entry )", blob):
        m = re.search(r'd:title="([^"]{1,60})"', entry)
        if not m:
            continue
        headword = html.unescape(m.group(1)).lower().strip()
        if not headword or " " in headword and len(headword.split()) > 3:
            continue
        defs = list(re.finditer(r'<div class="def">(.*?)</div>', entry, re.S))
        for i, dm in enumerate(defs):
            # A quotation belongs to the definition it follows, so the search
            # for it must stop at the NEXT definition. Scanning a fixed window
            # instead lets a citation jump senses and vouch for the wrong one --
            # that is how "gathered" ended up glossed "to gain; to win" on the
            # strength of a Gen. xxv. 8 citation belonging to another sense.
            stop = defs[i + 1].start() if i + 1 < len(defs) else len(entry)
            after = entry[dm.end():stop]
            window = entry[max(0, dm.start() - 500):stop]
            au = re.search(r'<div class="au">(.*?)</div>', after, re.S)
            mark = re.search(r'<div class="mark">\[(.*?)\]', window, re.S)
            au_text = untag(au.group(1)) if au else ""
            definition = untag(dm.group(1))
            if not definition or len(definition) < 3:
                continue
            words[headword].append({
                "def": definition,
                "mark": untag(mark.group(1)) if mark else "",
                "au": au_text,
                "cited": bool(CITE_RE.match(au_text)),
            })
    return words


def kjv_vocabulary(path):
    """lowercase form -> occurrence count, for forms that appear lowercased."""
    data = json.load(open(path))
    freq = collections.Counter()
    lower = set()
    for chapters in data.values():
        for verses in chapters.values():
            for text in verses:
                for w in WORD_RE.findall(text):
                    freq[w.lower()] += 1
                    if w[0].islower():
                        lower.add(w.lower())
    return freq, lower


def candidate_headwords(form):
    """Webster headwords an inflected KJV form might resolve to."""
    yield form
    for suf in SUFFIXES:
        if form.endswith(suf) and len(form) - len(suf) >= 3:
            base = form[: -len(suf)]
            yield base
            yield base + "e"
            if len(base) > 3 and base[-1] == base[-2]:
                yield base[:-1]
            if base.endswith("i"):
                yield base[:-1] + "y"


def usable(sense):
    """A sense is usable only if its body is a definition, not an inflection note."""
    return len(sense["def"]) >= 12 and not STUB_RE.match(sense["def"])


def choose_sense(senses, kjv_freq):
    """Return (sense, confidence, auto) -- auto says whether it may ship unreviewed.

    Only a scripture-cited sense ships automatically. Webster is naming a verse
    and saying "this sense, here", which is as direct as provenance gets.

    Everything else is a proposal for review, because the obvious-looking rules
    are wrong often enough to matter:

      an [Obs.] marker says a sense is dead, NOT that the KJV uses it. The KJV
      usually uses the ordinary sense. Trusting the marker glosses "hosts" as
      "any animal affording lodgment to a parasite" instead of "armies", and
      "turn" as "a court of record held by the sheriff".

      a single-sense entry has nothing to disambiguate, but only if the headword
      match is right. "kine" collides with a C.G.S. velocity unit, "why" with a
      dialect word for a heifer.

    Both classes are still worth proposing -- a human says yes or no far faster
    than writing a gloss from scratch -- but neither is safe to assert.
    """
    senses = [s for s in senses if usable(s)]
    if not senses:
        return None, "stub", False
    for s in senses:
        if s["cited"]:
            return s, "cited", True
    for s in senses:
        if ARCHAIC_RE.search(s["mark"]):
            return s, "marked", False
    if len(senses) == 1 and kjv_freq <= 50:
        return senses[0], "single", False
    return senses[0], "ambiguous", False


def truncate(text, limit=190):
    """Webster senses run long; keep the popover to a couple of lines."""
    text = text.rstrip()
    if len(text) <= limit:
        return text
    cut = text[:limit]
    for sep in ("; ", ", ", " "):
        i = cut.rfind(sep)
        if i > limit * 0.6:
            return cut[:i].rstrip(" ,;") + "…"
    return cut.rstrip() + "…"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", default=DEFAULT_BUNDLE)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--review", default=DEFAULT_REVIEW)
    args = ap.parse_args()

    if not os.path.exists(args.bundle):
        log(f"Webster's Body.data not found at {args.bundle}")
        log("Pass --bundle PATH pointing at a Webster's 1913 Dictionary.app bundle.")
        return 1

    log("Decompressing Webster's 1913…")
    words = parse_entries(decompress_body(args.bundle))
    log(f"  {len(words):,} headwords, {sum(len(v) for v in words.values()):,} senses")

    log("Reading KJV vocabulary…")
    freq, lower = kjv_vocabulary(KJV_JSON)
    log(f"  {len(lower):,} lowercase forms across {sum(freq.values()):,} tokens")

    glossary, review = {}, {}
    counts = collections.Counter()
    for form in sorted(lower):
        if form in FUNCTION_WORDS:
            counts["function-word"] += 1
            continue
        if freq[form] > MAX_OCCURRENCES:
            counts["too-common"] += 1
            continue
        entry = headword = None
        for cand in candidate_headwords(form):
            if cand in words:
                entry, headword = words[cand], cand
                break
        if entry is None:
            counts["no-entry"] += 1
            continue
        sense, confidence, auto = choose_sense(entry, freq[form])
        counts[confidence] += 1
        if sense is None:
            continue
        record = {
            "headword": headword,
            "gloss": truncate(sense["def"]),
            "confidence": confidence,
            "occurrences": freq[form],
            "source": "Webster's Unabridged Dictionary (1913), public domain",
        }
        if sense["mark"]:
            record["mark"] = sense["mark"]
        if sense["cited"]:
            record["citation"] = sense["au"]
        if auto:
            glossary[form] = record
        else:
            # A proposal, not an assertion. Reviewing is a yes/no against the
            # alternatives rather than writing a definition from nothing.
            record["alternatives"] = [truncate(s["def"], 120) for s in entry[:6]
                                      if s["def"] != sense["def"]]
            review[form] = record

    payload = {
        "_source": "Webster's Unabridged Dictionary (1913). Public domain.",
        "_generator": "scripts/build_glossary.py",
        "_note": "Glosses are verbatim Webster's senses. Sense selection is derived "
                 "from Webster's own scripture citations and [Obs.]/[Archaic] markers.",
        "entries": glossary,
    }
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fh:
        json.dump(payload, fh, indent=1, sort_keys=True, ensure_ascii=False)
    with open(args.review, "w") as fh:
        json.dump(review, fh, indent=1, sort_keys=True, ensure_ascii=False)

    log("")
    log(f"  SHIPPED")
    log(f"    cited    {counts['cited']:>5}   Webster cites scripture on the sense")
    log(f"  PROPOSED (needs review, not shipped)")
    log(f"    marked   {counts['marked']:>5}   [Obs.] / [Archaic] sense exists")
    log(f"    single   {counts['single']:>5}   one sense, rare in KJV")
    log(f"    ambig    {counts['ambiguous']:>5}   several modern senses")
    log(f"  ---------------------")
    log(f"  glossary   {len(glossary):>5}  -> {args.out}")
    log(f"  review     {len(review):>5}  -> {args.review}")
    log(f"  no entry   {counts['no-entry']:>5}   (proper nouns, inflections)")
    log(f"  excluded   {counts['function-word']:>5}   function words")
    log(f"             {counts['too-common']:>5}   over {MAX_OCCURRENCES} occurrences")
    log(f"             {counts['stub']:>5}   Webster body was an inflection note")
    return 0


if __name__ == "__main__":
    sys.exit(main())
