#!/usr/bin/env python3
"""
Build kjv-glossary.json from Webster's Unabridged Dictionary (1913, public domain).

Every gloss in the output is lifted verbatim from Webster's. Nothing is authored
here and nothing is generated by a model -- the whole point is that each entry
traces back to a real dictionary sense, with the provenance recorded per entry.

Source: an Apple Dictionary.app bundle built from the public-domain Webster's
1913 text. Body.data is a run of zlib streams (0x78 0xda); each decompresses to
XML holding <d:entry> elements with class="def" / "mark" / "au" sub-divs.

A gloss is keyed on the surface form, so whatever it says is asserted at EVERY
occurrence of that word in the Bible. Every rule below exists because a looser
one shipped something false about scripture.

An entry ships only when all of these hold:

  monosemous      exactly one usable Webster sense. With one sense there is
                  nothing to over-apply and nothing to disambiguate.
  clean headword  an exact match, or a suffix-stripped one where exactly ONE
                  candidate exists in Webster.
  not a homograph the entry carried no inflection note. If Webster says this
                  spelling is the plural or preterit of another word, the
                  remaining sense belongs to a different word entirely.
  real definition the sense body is a definition, not a grammar label or a
                  bare cross-reference.

with one deliberate exception:

  cited-dominant  a polysemous word may ship on a scripture-cited sense when
                  >=80% of its KJV occurrences fall inside the cited book. All
                  10 "taches" are in Exodus and Webster cites Ex. xxvi. 6, so
                  that sense is not one usage among many -- it is the usage.

Rules tried and rejected, each having asserted something false:

  [Obs.] markers      a dead sense is not the sense the KJV uses. Glossed
                      "hosts" as "any animal affording lodgment to a parasite"
                      and "turn" as "a court of record held by the sheriff".
  bare citation       licenses a sense AT THE CITED VERSE only. Webster cites
                      Lev. xxv. 4 for "sabbath" = the seventh YEAR -- true
                      there, wrong for most of the other 136 occurrences. This
                      is what cited-dominant replaces.
  citation by window  scanning a fixed span for a quotation lets a trailing
                      idiom certify an unrelated sense. Webster keeps phrases
                      in <div class="cs">; "To lift up ... John viii. 28" made
                      "lift" ship as "to steal cattle".
  first candidate     being first in a suffix list is not evidence. Stripping
                      -s from "plates" yields both "plat" and "plate"; the
                      first won, and the metal plates of Exodus were glossed
                      "to braid".
  survivor of a stub  filtering an inflection note can make a two-sense entry
                      look monosemous, promoting a rare homograph to sole
                      survivor: "feet" as "fact; performance", "slew" as "a wet
                      place; a river inlet".

Everything not shipped becomes a proposal in the review file, with its
alternatives, so review is a yes/no rather than writing a definition.

Usage:
  python3 scripts/build_glossary.py [--bundle PATH] [--out PATH] [--review PATH]
"""

import argparse
import collections
import html
import json
import os
import re
import sys
import zlib

DEFAULT_BUNDLE = os.path.expanduser(
    "~/Library/Dictionaries/websters-1913.dictionary/Contents/Resources/Body.data"
)
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUT = os.path.join(REPO, "src/main/resources/data/kjv-glossary.json")
DEFAULT_REVIEW = os.path.join(REPO, "scripts/glossary-needs-review.json")
KJV_JSON = os.path.join(REPO, "src/main/resources/data/kjv.json")

# Webster cites scripture as "Ex. xxvi. 6." / "1 Cor. xiii. 4." -- an abbreviated
# book, a roman-numeral chapter, then a verse.
BOOKS = (
    r"(?:Gen|Ex|Exod|Lev|Num|Deut|Josh|Judg|Ruth|Sam|Kings|Kin|Chron|Ezra|Neh|Esth|Job|Ps"
    r"|Prov|Eccl|Cant|Song|Isa|Jer|Lam|Ezek|Dan|Hos|Joel|Amos|Obad|Jonah|Mic|Nah|Hab"
    r"|Zeph|Hag|Zech|Mal|Matt|Mark|Luke|John|Acts|Rom|Cor|Gal|Eph|Phil|Col|Thess|Tim"
    r"|Titus|Philem|Heb|James|Jas|Pet|Jude|Rev)"
)
CITE_RE = re.compile(r"^\s*(?:[1-3]\s*)?" + BOOKS + r"\.?\s*[ivxlc]+[\.\s]", re.I)
ARCHAIC_RE = re.compile(r"\b(obs|archaic)\b", re.I)
WORD_RE = re.compile(r"[A-Za-z][A-Za-z'\-]*")

# Suffixes stripped when mapping an inflected KJV form back to a Webster
# headword: taches -> tache, coupleth -> couple. Longest first so "eth" is
# tried before "th".
SUFFIXES = ["eth", "est", "ing", "es", "ed", "st", "th", "s", "d", "n"]

# Webster carries a long-dead sense for almost every function word -- "god" as a
# variant of "good", "not" as a contraction of "wot not", "me" as a form of
# "men". Selecting those produces a gloss that is both useless and, on a page of
# scripture, actively false. Function words are a closed grammatical class, so
# excluding them wholesale costs nothing: no reader of the KJV is stuck on "the".
FUNCTION_WORDS = set("""
a an the and or but nor for yet so if then than that this these those there here
of in on at by to from with without within into onto upon over under above below
through between among against about after before during until till since up down
out off again further once
i me my mine myself we us our ours ourselves you your yours yourself yourselves
he him his himself she her hers herself it its itself they them their theirs
themselves who whom whose which what whatever whoever whomever
thee thou thy thine ye yourself
am is are was were be been being have has had having do does did doing done
shall should will would may might must can could let lets
not no nor none nothing all any both each few more most other some such only own
same very too as is came come go went gone said say says
one two three four five six seven eight nine ten eleven twelve twenty thirty
forty fifty sixty seventy eighty ninety hundred thousand first second third
therein thereof thereon thereto therewith thereby wherein whereof whereby
whereon whereto herein hereof hereby hereto moreover furthermore however
cannot whosoever whatsoever whensoever wheresoever thyself himself herself
itself myself ourselves yourselves themselves
""".split())

# Webster's entry body sometimes holds an inflection note rather than a
# definition ("imperfect or past participle", "plural of ..."). Useless in a
# popover, and in a few cases actively misleading.
STUB_RE = re.compile(
    r"^\s*(?:the\s+|a\s+|an\s+)?(?:"
    # inflection notes -- "imperfect or past participle", "the past or preterit
    # tense of Arise", "the second-person singular imperfect"
    r"imperfect|preterit|past\b|present\b|p\.\s*p\b|pl\b|plural\b|sing(?:ular)?\b"
    r"|first-?\s*or\s*third-?\s*person|second-?\s*person|third-?\s*person"
    # bare part-of-speech labels -- "adjective or noun"
    r"|adjective\b|adverb\b|noun\b|verb\b|participle\b"
    # pure cross-references carry no definition of their own
    r"|see\s+\w+\.?\s*$|same\s+as\s+\w+\.?\s*$|of\s+\w+\.?\s*$|obs\b"
    r")",
    re.I,
)

# Above this many occurrences a word is part of the KJV's ordinary furniture and
# a reader is not tripping over it. Keeps the glossary to words that actually
# stop someone: shew (228) stays, saith (1262) goes.
MAX_OCCURRENCES = 300


def log(msg):
    print(msg, file=sys.stderr)


def decompress_body(path):
    """Concatenate every zlib stream in an Apple Dictionary Body.data."""
    raw = open(path, "rb").read()
    magic = re.compile(rb"\x78[\x01\x9c\xda]")
    out, i, n = [], 0x40, 0
    while True:
        m = magic.search(raw, i)
        if not m:
            break
        j = m.start()
        try:
            dec = zlib.decompressobj()
            chunk = dec.decompress(raw[j:])
            if len(chunk) > 500:
                out.append(chunk)
                n += 1
                i = len(raw) - len(dec.unused_data)
                continue
        except zlib.error:
            pass
        i = j + 2
    log(f"  {n} zlib streams -> {sum(len(c) for c in out):,} bytes of XML")
    return b"".join(out).decode("utf-8", "replace")


def untag(s):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", s))).strip()


def parse_entries(blob):
    """headword -> [sense], each sense carrying its def, marker and citation."""
    words = collections.defaultdict(list)
    for entry in re.split(r"(?=<d:entry )", blob):
        m = re.search(r'd:title="([^"]{1,60})"', entry)
        if not m:
            continue
        headword = html.unescape(m.group(1)).lower().strip()
        if not headword or " " in headword and len(headword.split()) > 3:
            continue
        # Part of speech is declared per entry, ahead of the senses. Needed to
        # reject a plural noun that matched a verb-only headword.
        pos = {untag(p).lower().strip() for p in
               re.findall(r'<div class="pos">(.*?)</div>', entry, re.S)}

        defs = list(re.finditer(r'<div class="def">(.*?)</div>', entry, re.S))
        # Webster puts idioms and phrasal senses in a trailing <div class="cs">
        # block -- "To lift up ... John viii. 28." Those citations belong to the
        # PHRASE, not to the headword, so the last definition's search must stop
        # there. Without this, "lift" ships as "to steal cattle" certified by a
        # citation that is really about being lifted up on the cross; "break",
        # "gather" and "work" corrupt the same way.
        cs = re.search(r'<div class="cs">', entry)
        cs_at = cs.start() if cs else len(entry)
        for i, dm in enumerate(defs):
            # A quotation belongs to the definition it follows, so the search
            # for it must stop at the NEXT definition -- or at the phrase block,
            # whichever comes first.
            nxt = defs[i + 1].start() if i + 1 < len(defs) else len(entry)
            stop = min(nxt, cs_at) if cs_at > dm.end() else nxt
            after = entry[dm.end():stop]
            window = entry[max(0, dm.start() - 500):stop]
            au = re.search(r'<div class="au">(.*?)</div>', after, re.S)
            mark = re.search(r'<div class="mark">\[(.*?)\]', window, re.S)
            au_text = untag(au.group(1)) if au else ""
            definition = untag(dm.group(1))
            if not definition or len(definition) < 3:
                continue
            words[headword].append({
                "def": definition,
                "mark": untag(mark.group(1)) if mark else "",
                "au": au_text,
                "cited": bool(CITE_RE.match(au_text)),
                "pos": pos,
            })
    return words


def kjv_vocabulary(path):
    """lowercase form -> occurrence count, for forms that appear lowercased."""
    data = json.load(open(path))
    freq = collections.Counter()
    lower = set()
    locations = collections.defaultdict(collections.Counter)
    for book, chapters in data.items():
        for verses in chapters.values():
            for text in verses:
                for w in WORD_RE.findall(text):
                    freq[w.lower()] += 1
                    locations[w.lower()][book] += 1
                    if w[0].islower():
                        lower.add(w.lower())
    return freq, lower, locations


def candidate_headwords(form):
    """Webster headwords an inflected KJV form might resolve to."""
    for suf in SUFFIXES:
        if form.endswith(suf) and len(form) - len(suf) >= 3:
            base = form[: -len(suf)]
            yield base
            yield base + "e"
            if len(base) > 3 and base[-1] == base[-2]:
                yield base[:-1]
            if base.endswith("i"):
                yield base[:-1] + "y"


PLURALISH_RE = re.compile(r"(?:[^aeiou]s|es)$")

# Share of a word's KJV occurrences that must fall inside the book Webster cites
# before a cited sense is trusted for the word everywhere. See cited_coverage.
CITED_COVERAGE_MIN = 0.8

CITE_BOOK_RE = re.compile(r"^\s*(?:[1-3]\s*)?([A-Za-z]+)\.?", re.I)
BOOK_ALIASES = {"cant": "song", "song": "song", "philem": "philemon",
                "jas": "james", "kin": "kings", "exod": "exodus"}


def cited_book(citation, kjv_books):
    """KJV book names a Webster citation like '1 Sam. xvi. 13.' refers to.

    Numbered volumes collapse together -- a sense used across 1 and 2 Samuel is
    one usage -- so the leading digit is dropped and the match is on the base
    name.
    """
    m = CITE_BOOK_RE.match(citation or "")
    if not m:
        return set()
    abbr = BOOK_ALIASES.get(m.group(1).lower(), m.group(1).lower())
    hits = set()
    for b in kjv_books:
        base = re.sub(r"^[1-3]\s+", "", b).lower()
        if base.startswith(abbr) or abbr.startswith(base):
            hits.add(b)
    return hits


def cited_coverage(form, citation, locations):
    """Fraction of this form's KJV occurrences inside the cited book.

    A scripture citation licenses a sense at the verse it names. Whether that
    sense governs the word *everywhere* is a separate question, and the KJV text
    answers it: if the word only ever appears in the book Webster cites, the
    cited sense is the word's meaning. If it is scattered across the canon, the
    citation is describing one usage among many.

    tache  -> all 10 occurrences in Exodus, cited Ex. xxvi. 6  -> 1.00, trust it
    sabbath-> 137 occurrences across 30+ books, cited Lev. xxv -> 0.12, do not
    """
    counts = locations.get(form)
    if not counts:
        return 0.0
    books = cited_book(citation, counts.keys())
    if not books:
        return 0.0
    total = sum(counts.values())
    return sum(counts[b] for b in books) / total if total else 0.0


def resolve_headword(form, words):
    """(headword, senses, resolution) for a KJV form.

    Taking the *first* candidate that happens to exist is how "plates" ended up
    glossed "to braid": stripping -s yields both "plat" and "plate", and "plat"
    was tried first. Being first in a suffix list is not evidence.

    An inflection is only trusted when the dictionary leaves no choice -- exactly
    one candidate exists. Two candidates means the data cannot say which is the
    lemma, so it goes to review rather than being guessed. That catches "plates",
    "whited" (whit/white) and "fared" (far/fare).
    """
    if form in words:
        return form, words[form], "exact"
    found = sorted({c for c in candidate_headwords(form) if c in words})
    if not found:
        return None, None, "none"
    if len(found) > 1:
        return found[0], words[found[0]], "ambiguous"
    hw = found[0]
    senses = words[hw]
    # A plural noun that resolved to a verb-only headword is not this word.
    # "calves" is unambiguous by candidate count, but "calve" is a verb -- "to
    # bring forth a calf" -- and the KJV's calves are animals, not an action.
    if PLURALISH_RE.search(form):
        pos = set().union(*(s.get("pos", set()) for s in senses)) if senses else set()
        if pos and not any("noun" in p for p in pos):
            return hw, senses, "pos-mismatch"
    return hw, senses, "inflection"


def usable(sense):
    """A sense is usable only if its body is a definition, not an inflection note."""
    return len(sense["def"]) >= 12 and not STUB_RE.match(sense["def"])


def choose_sense(senses, kjv_freq, coverage=0.0):
    """Return (sense, confidence, auto) -- auto says whether it may ship unreviewed.

    Only a scripture-cited sense ships automatically. Webster is naming a verse
    and saying "this sense, here", which is as direct as provenance gets.

    Everything else is a proposal for review, because the obvious-looking rules
    are wrong often enough to matter:

      an [Obs.] marker says a sense is dead, NOT that the KJV uses it. The KJV
      usually uses the ordinary sense. Trusting the marker glosses "hosts" as
      "any animal affording lodgment to a parasite" instead of "armies", and
      "turn" as "a court of record held by the sheriff".

      a single-sense entry has nothing to disambiguate, but only if the headword
      match is right. "kine" collides with a C.G.S. velocity unit, "why" with a
      dialect word for a heifer.

    Both classes are still worth proposing -- a human says yes or no far faster
    than writing a gloss from scratch -- but neither is safe to assert.
    """
    kept = [s for s in senses if usable(s)]
    if not kept:
        return None, "stub", False
    # A stub sense ("plural of Foot", "imperfect of Slay") is Webster telling us
    # this spelling is an inflection of another word. Dropping it as unusable
    # then treating what remains as the word's only sense promotes a rare
    # homograph to sole survivor: "feet" ships as "fact; performance", "slew" as
    # "a wet place; a river inlet", "seen" as "versed; skilled". If the entry
    # carried an inflection note at all, this spelling is not its own word.
    if len(kept) != len(senses):
        return kept[0], "homograph-of-inflection", False
    senses = kept

    # A citation licenses a sense AT THE CITED VERSE. It says nothing about the
    # word's other occurrences, and a glossary keyed on the surface form applies
    # to all of them. Webster cites Lev. xxv. 4 for "sabbath" meaning the seventh
    # YEAR -- true there, wrong for most of the other 136 occurrences. Same for
    # "adultery" (faithlessness in religion, Jer. iii. 9) and "horns".
    #
    # So a citation is only safe to ship globally when the word has nothing else
    # to mean: one usable sense, no polysemy, nothing to get wrong. Cited senses
    # on polysemous words keep their citation and go to review, where the verse
    # scoping is a human's call.
    if len(senses) == 1:
        s = senses[0]
        why = "single-cited" if s["cited"] else (
            "single-marked" if ARCHAIC_RE.search(s["mark"]) else "single")
        return s, why, True

    for s in senses:
        if s["cited"]:
            if coverage >= CITED_COVERAGE_MIN:
                # The word lives in the book Webster cites, so the cited sense
                # is not one usage among many -- it is the usage.
                return s, "cited-dominant", True
            return s, "cited-polysemous", False
    for s in senses:
        if ARCHAIC_RE.search(s["mark"]):
            return s, "marked", False
    return senses[0], "ambiguous", False


def truncate(text, limit=190):
    """Webster senses run long; keep the popover to a couple of lines."""
    text = text.rstrip()
    if len(text) <= limit:
        return text
    cut = text[:limit]
    for sep in ("; ", ", ", " "):
        i = cut.rfind(sep)
        if i > limit * 0.6:
            return cut[:i].rstrip(" ,;") + "…"
    return cut.rstrip() + "…"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", default=DEFAULT_BUNDLE)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--review", default=DEFAULT_REVIEW)
    args = ap.parse_args()

    if not os.path.exists(args.bundle):
        log(f"Webster's Body.data not found at {args.bundle}")
        log("Pass --bundle PATH pointing at a Webster's 1913 Dictionary.app bundle.")
        return 1

    log("Decompressing Webster's 1913…")
    words = parse_entries(decompress_body(args.bundle))
    log(f"  {len(words):,} headwords, {sum(len(v) for v in words.values()):,} senses")

    log("Reading KJV vocabulary…")
    freq, lower, locations = kjv_vocabulary(KJV_JSON)
    log(f"  {len(lower):,} lowercase forms across {sum(freq.values()):,} tokens")

    glossary, review = {}, {}
    counts = collections.Counter()
    for form in sorted(lower):
        if form in FUNCTION_WORDS:
            counts["function-word"] += 1
            continue
        if freq[form] > MAX_OCCURRENCES:
            counts["too-common"] += 1
            continue
        headword, entry, resolution = resolve_headword(form, words)
        if resolution == "none":
            counts["no-entry"] += 1
            continue
        cited_at = next((s["au"] for s in entry if s.get("cited")), "")
        coverage = cited_coverage(form, cited_at, locations)
        sense, confidence, auto = choose_sense(entry, freq[form], coverage)
        # A shaky headword match disqualifies the entry however good the sense
        # looks -- the sense is for a different word.
        if resolution in ("ambiguous", "pos-mismatch"):
            counts["hw-" + resolution] += 1
            auto = False
            confidence = resolution
        counts[confidence] += 1
        if sense is None:
            continue
        record = {
            "headword": headword,
            "gloss": truncate(sense["def"]),
            "confidence": confidence,
            "resolution": resolution,
            "occurrences": freq[form],
            "source": "Webster's Unabridged Dictionary (1913), public domain",
        }
        if sense["mark"]:
            record["mark"] = sense["mark"]
        if sense["cited"]:
            record["citation"] = sense["au"]
            record["citedBookShare"] = round(coverage, 3)
        if auto:
            glossary[form] = record
        else:
            # A proposal, not an assertion. Reviewing is a yes/no against the
            # alternatives rather than writing a definition from nothing.
            record["alternatives"] = [truncate(s["def"], 120) for s in entry[:6]
                                      if s["def"] != sense["def"]]
            review[form] = record

    payload = {
        "_source": "Webster's Unabridged Dictionary (1913). Public domain.",
        "_generator": "scripts/build_glossary.py",
        "_note": "Glosses are verbatim Webster's senses. Sense selection is derived "
                 "from Webster's own scripture citations and [Obs.]/[Archaic] markers.",
        "entries": glossary,
    }
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fh:
        json.dump(payload, fh, indent=1, sort_keys=True, ensure_ascii=False)
    with open(args.review, "w") as fh:
        json.dump(review, fh, indent=1, sort_keys=True, ensure_ascii=False)

    log("")
    log(f"  SHIPPED (monosemous -- one usable sense, nothing to over-apply)")
    log(f"    single-cited  {counts['single-cited']:>5}   + Webster cites scripture")
    log(f"    single-marked {counts['single-marked']:>5}   + [Obs.] / [Archaic]")
    log(f"    single        {counts['single']:>5}   unmarked")
    log(f"    cited-dominant{counts['cited-dominant']:>5}   polysemous, but the word lives in the cited book")
    log(f"  PROPOSED (needs review, not shipped)")
    log(f"    cited-poly    {counts['cited-polysemous']:>5}   cited, but word has other senses")
    log(f"    marked        {counts['marked']:>5}   [Obs.] / [Archaic] among several")
    log(f"    ambiguous     {counts['ambiguous']:>5}   several modern senses")
    log(f"    homograph     {counts['homograph-of-inflection']:>5}   spelling is an inflection of another word")
    log(f"    bad-headword  {counts['hw-ambiguous']:>5}   inflection matched >1 candidate")
    log(f"    pos-mismatch  {counts['hw-pos-mismatch']:>5}   plural noun hit a verb-only headword")
    log(f"  ---------------------")
    log(f"  glossary   {len(glossary):>5}  -> {args.out}")
    log(f"  review     {len(review):>5}  -> {args.review}")
    log(f"  no entry   {counts['no-entry']:>5}   (proper nouns, inflections)")
    log(f"  excluded   {counts['function-word']:>5}   function words")
    log(f"             {counts['too-common']:>5}   over {MAX_OCCURRENCES} occurrences")
    log(f"             {counts['stub']:>5}   Webster body was an inflection note")
    return 0


if __name__ == "__main__":
    sys.exit(main())
